HW6 is completed
Lanworm/OTUS_GO pull request #6
Opened 2024-03-19 12:49 UTC by Lanworm

## Домашнее задание №6 «Пайплайн»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [ ] Я сравнил объем кода с объемом авторского решения. [Зачем сверять объем кода?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D1%81%D0%B2%D0%B5%D1%80%D1%8F%D1%82%D1%8C-%D0%BE%D0%B1%D1%8A%D0%B5%D0%BC-%D0%BA%D0%BE%D0%B4%D0%B0)
  - pipeline.go ~55 строк

### Критерии оценки
- [ ] CI-пайплайн зелёный - 5 баллов
- [ ] Добавлены новые юнит-тесты - до 2 баллов
- [ ] Понятность и чистота кода - до 3 баллов

#### Зачёт от 7 баллов

2024-03-19 15:40 UTC, agneum requested changes
Спасибо за вариант решения

2024-03-19 15:40 UTC, agneum commented on hw06_pipeline_execution/pipeline.go
> +	for task := range in {
По условию задания
> обработка последующего элемента входных данных должна происходить **без ожидания завершения всего пайплайна** для текущего элемента.

https://github.com/Lanworm/OTUS_GO/tree/master/hw06_pipeline_execution

То есть перебор входных данных (кстати, почему входные данные называются `task`?) не удовлетворяет условию.

2024-03-19 15:40 UTC, agneum commented on hw06_pipeline_execution/pipeline.go
> +		resultArr = append(resultArr, nil)
Очень сложная логика со слайсами флагов и результатов.

Предлагаю начать с реализации простого сценария:
`in` -> `stage` -> `stage` -> ... -> `out`

Затем необходимо добавить обработку канала `done`. Поскольку сигнатуру `Stage` менять нельзя, я бы добавил функцию-обертку, которую можно встроить в пайплайн, и которая будет останавливать пайплайн через дополнительный сигнальный канал

2024-03-21 14:55 UTC, agneum requested changes
Спасибо за правки. Выглядит лучше, однако функциональность пока не реализована

2024-03-21 14:55 UTC, agneum commented on hw06_pipeline_execution/pipeline.go
> +	out := stages[0](in)
Почему первый `stage` обрабатывается два раза - здесь и внутри `exec`?
А если `stages` пуст?

2024-03-21 14:55 UTC, agneum commented on hw06_pipeline_execution/pipeline.go
> +		out = exec(done, out, s)
Мне кажется, что если `stage` не передавать внутрь функции, то запись будет выглядеть немного проще

2024-03-21 14:55 UTC, agneum commented on hw06_pipeline_execution/pipeline.go
> +		for range intStream {
Конструкция выглядит достаточно странно: перебор элементов канала, которые никак не используются. При этом, если в канале не будет новых элементов, то прервать пайплайн через `done` не получится

Более подходящим здесь будет бесконечный `for` с `select` в теле цикла

2024-03-21 14:55 UTC, agneum commented on hw06_pipeline_execution/pipeline.go
> +			case resultStream <- stage(intStream):
Предложил бы перенести `stage` в на уровень выше, в место вызова функции. А здесь можно перекладывать элементы из входного канала в выходной, проверяя, что входной канал не закрыт.

2024-03-21 14:55 UTC, agneum commented on hw06_pipeline_execution/pipeline.go
> +	intStream = resultStream
Не понятно, что предполагалось сделать

2024-03-22 15:15 UTC, agneum requested changes

2024-03-22 15:15 UTC, agneum commented on hw06_pipeline_execution/pipeline.go
> +	out := make(Out)
Если `stages` нет, то вернётся пустой канал. В этом случае должен вернуться входной `in`

2024-03-22 15:15 UTC, agneum commented on hw06_pipeline_execution/pipeline.go
> +		out = s(in)
Чтобы получился пайплайн, каждая стадия должна принимать результат предыдущей, но не входной канал

2024-03-22 15:15 UTC, agneum commented on hw06_pipeline_execution/pipeline.go
> +		exec(done, out, in)
Почему оба канала в аргументах?

2024-03-22 15:15 UTC, agneum commented on hw06_pipeline_execution/pipeline.go
> +				in = out
Не понимаю, какая идея была заложена в этих строках
Если предполагалось переложить значения из одного канала в другой, то нужно прочитать явно значение из одного канала в переменную и записать значение переменной в другой канал

2024-03-23 05:39 UTC, Lanworm commented on hw06_pipeline_execution/pipeline.go
> +		out = s(in)
Как изначально передать входной канал в цикл? как передавать результат от предыдущей к следующей? Должна быть какая-то переменная промежуточная?

2024-03-25 15:09 UTC, agneum approved these changes
Спасибо за правки. Выглядит хорошо.
Принято

2024-03-25 15:09 UTC, agneum commented on hw06_pipeline_execution/pipeline.go
> +	for _, stage := range stages {
Можно перед циклом обернуть канал `in` в `exec`, чтобы иметь возможность остановить пайплайн, даже если нет `stages`

2024-04-07 07:17 UTC, merged